from flask import Flask, render_template, jsonify

app = Flask(__name__)

# 元素データ（すべての元素）
elements = [
    {"symbol": "H", "row": 1, "col": 1, "name": "水素", "atomic_number": 1, "description": "最も軽い元素。宇宙で最も豊富な元素。"},
    {"symbol": "He", "row": 1, "col": 18, "name": "ヘリウム", "atomic_number": 2, "description": "非常に軽い元素で、気球に使われる。"},
    {"symbol": "Li", "row": 2, "col": 1, "name": "リチウム", "atomic_number": 3, "description": "アルカリ金属で、電池に使われる。"},
    {"symbol": "Be", "row": 2, "col": 2, "name": "ベリリウム", "atomic_number": 4, "description": "強い金属で、航空機の部品に使われる。"},
    {"symbol": "B", "row": 2, "col": 13, "name": "ホウ素", "atomic_number": 5, "description": "半導体材料として使われる。"},
    {"symbol": "C", "row": 2, "col": 14, "name": "炭素", "atomic_number": 6, "description": "生命の基礎を成す元素。"},
    {"symbol": "N", "row": 2, "col": 15, "name": "窒素", "atomic_number": 7, "description": "空気の大部分を占める元素。"},
    {"symbol": "O", "row": 2, "col": 16, "name": "酸素", "atomic_number": 8, "description": "生命に欠かせない元素。"},
    {"symbol": "F", "row": 2, "col": 17, "name": "フッ素", "atomic_number": 9, "description": "非常に反応性の高い元素。"},
    {"symbol": "Ne", "row": 2, "col": 18, "name": "ネオン", "atomic_number": 10, "description": "無色、無臭、無味の気体で、看板に使われる。"},
    {"symbol": "Na", "row": 3, "col": 1, "name": "ナトリウム", "atomic_number": 11, "description": "食塩の成分としてよく知られている。"},
    {"symbol": "Mg", "row": 3, "col": 2, "name": "マグネシウム", "atomic_number": 12, "description": "軽くて強い金属。"},
    {"symbol": "Al", "row": 3, "col": 13, "name": "アルミニウム", "atomic_number": 13, "description": "軽くて耐食性の高い金属。"},
    {"symbol": "Si", "row": 3, "col": 14, "name": "ケイ素", "atomic_number": 14, "description": "半導体としてよく使われる元素。"},
    {"symbol": "P", "row": 3, "col": 15, "name": "リン", "atomic_number": 15, "description": "生物にとって重要な元素。"},
    {"symbol": "S", "row": 3, "col": 16, "name": "硫黄", "atomic_number": 16, "description": "酸性雨の原因となる元素。"},
    {"symbol": "Cl", "row": 3, "col": 17, "name": "塩素", "atomic_number": 17, "description": "塩化ナトリウム（食塩）などに含まれる元素。"},
    {"symbol": "Ar", "row": 3, "col": 18, "name": "アルゴン", "atomic_number": 18, "description": "無色、無臭、無味の気体。"},
    {"symbol": "K", "row": 4, "col": 1, "name": "カリウム", "atomic_number": 19, "description": "バナナに多く含まれる。"},
    {"symbol": "Ca", "row": 4, "col": 2, "name": "カルシウム", "atomic_number": 20, "description": "骨や歯の主成分。"},
    {"symbol": "Sc", "row": 4, "col": 3, "name": "スカンジウム", "atomic_number": 21, "description": "希少な金属元素の一つ。"},
    {"symbol": "Ti", "row": 4, "col": 4, "name": "チタン", "atomic_number": 22, "description": "強くて軽い金属。"},
    {"symbol": "V", "row": 4, "col": 5, "name": "バナジウム", "atomic_number": 23, "description": "高温に耐える金属。"},
    {"symbol": "Cr", "row": 4, "col": 6, "name": "クロム", "atomic_number": 24, "description": "錆びにくい金属。"},
    {"symbol": "Mn", "row": 4, "col": 7, "name": "マンガン", "atomic_number": 25, "description": "鉄と合金を作るために使われる。"},
    {"symbol": "Fe", "row": 4, "col": 8, "name": "鉄", "atomic_number": 26, "description": "最も一般的な金属元素。"},
    {"symbol": "Co", "row": 4, "col": 9, "name": "コバルト", "atomic_number": 27, "description": "強い磁力を持つ金属。"},
    {"symbol": "Ni", "row": 4, "col": 10, "name": "ニッケル", "atomic_number": 28, "description": "硬くて耐久性がある金属。"},
    {"symbol": "Cu", "row": 4, "col": 11, "name": "銅", "atomic_number": 29, "description": "電気をよく通す金属。"},
    {"symbol": "Zn", "row": 4, "col": 12, "name": "亜鉛", "atomic_number": 30, "description": "防錆材として使われる。"},
    {"symbol": "Ga", "row": 4, "col": 13, "name": "ガリウム", "atomic_number": 31, "description": "液体状態でも安定している金属。"},
    {"symbol": "Ge", "row": 4, "col": 14, "name": "ゲルマニウム", "atomic_number": 32, "description": "半導体材料として使用される。"},
    {"symbol": "As", "row": 4, "col": 15, "name": "ヒ素", "atomic_number": 33, "description": "有毒な元素で、農薬に使われることも。"},
    {"symbol": "Se", "row": 4, "col": 16, "name": "セレン", "atomic_number": 34, "description": "半導体材料やバッテリーに使われる。"},
    {"symbol": "Br", "row": 4, "col": 17, "name": "臭素", "atomic_number": 35, "description": "液体の非金属元素。"},
    {"symbol": "Kr", "row": 4, "col": 18, "name": "クリプトン", "atomic_number": 36, "description": "希ガスの一種で、光源に使われる。"},
    {"symbol": "Rb", "row": 5, "col": 1, "name": "ルビジウム", "atomic_number": 37, "description": "非常に反応性が高い金属。"},
    {"symbol": "Sr", "row": 5, "col": 2, "name": "ストロンチウム", "atomic_number": 38, "description": "蛍光灯に使われる。"},
    {"symbol": "Y", "row": 5, "col": 3, "name": "イットリウム", "atomic_number": 39, "description": "レアアース金属。"},
    {"symbol": "Zr", "row": 5, "col": 4, "name": "ジルコニウム", "atomic_number": 40, "description": "高温に耐える金属。"},
    {"symbol": "Nb", "row": 5, "col": 5, "name": "ニオブ", "atomic_number": 41, "description": "強度の高い金属。"},
    {"symbol": "Mo", "row": 5, "col": 6, "name": "モリブデン", "atomic_number": 42, "description": "耐久性のある金属。"},
    {"symbol": "Tc", "row": 5, "col": 7, "name": "テクネチウム", "atomic_number": 43, "description": "人工的に作られた元素。"},
    {"symbol": "Ru", "row": 5, "col": 8, "name": "ルテニウム", "atomic_number": 44, "description": "貴金属の一種。"},
    {"symbol": "Rh", "row": 5, "col": 9, "name": "ロジウム", "atomic_number": 45, "description": "貴金属で、触媒に使われる。"},
    {"symbol": "Pd", "row": 5, "col": 10, "name": "パラジウム", "atomic_number": 46, "description": "自動車の排ガス処理に使われる。"},
    {"symbol": "Ag", "row": 5, "col": 11, "name": "銀", "atomic_number": 47, "description": "非常に反射性の高い金属。"},
    {"symbol": "Cd", "row": 5, "col": 12, "name": "カドミウム", "atomic_number": 48, "description": "毒性があり、電池に使われる。"},
    {"symbol": "In", "row": 5, "col": 13, "name": "インジウム", "atomic_number": 49, "description": "非常に柔らかい金属。"},
    {"symbol": "Sn", "row": 5, "col": 14, "name": "スズ", "atomic_number": 50, "description": "腐食に強い金属。"},
    {"symbol": "Sb", "row": 5, "col": 15, "name": "アンチモン", "atomic_number": 51, "description": "合金や電子機器に使用される。"},
    {"symbol": "I", "row": 5, "col": 17, "name": "ヨウ素", "atomic_number": 53, "description": "有機化合物や医薬品に使われる。"},
    {"symbol": "Te", "row": 5, "col": 16, "name": "テルル", "atomic_number": 52, "description": "半導体材料として使用される。"},
    {"symbol": "Xe", "row": 5, "col": 18, "name": "キセノン", "atomic_number": 54, "description": "希ガスの一種。"},
    {"symbol": "Cs", "row": 6, "col": 1, "name": "セシウム", "atomic_number": 55, "description": "非常に反応性の高い金属。"},
    {"symbol": "Ba", "row": 6, "col": 2, "name": "バリウム", "atomic_number": 56, "description": "蛍光灯の塗料に使用される。"},
    {"symbol": "La", "row": 9, "col": 4, "name": "ランタン", "atomic_number": 57, "description": "希土類元素の一つ。"},
    {"symbol": "Ce", "row": 9, "col": 5, "name": "セリウム", "atomic_number": 58, "description": "自動車の触媒に使われる。"},
    {"symbol": "Pr", "row": 9, "col": 6, "name": "プラセオジウム", "atomic_number": 59, "description": "レアアース金属。"},
    {"symbol": "Nd", "row": 9, "col": 7, "name": "ネオジウム", "atomic_number": 60, "description": "強力な磁石に使われる。"},
    {"symbol": "Pm", "row": 9, "col": 8, "name": "プロメチウム", "atomic_number": 61, "description": "人工的に作られる元素。"},
    {"symbol": "Sm", "row": 9, "col": 9, "name": "サマリウム", "atomic_number": 62, "description": "強力な永久磁石に使用される。"},
    {"symbol": "Eu", "row": 9, "col": 10, "name": "ユウロピウム", "atomic_number": 63, "description": "蛍光体やランプに使われる。"},
    {"symbol": "Gd", "row": 9, "col": 11, "name": "ガドリニウム", "atomic_number": 64, "description": "医療機器に使用される。"},
    {"symbol": "Tb", "row": 9, "col": 12, "name": "テルビウム", "atomic_number": 65, "description": "磁気記録媒体に使用される。"},
    {"symbol": "Dy", "row": 9, "col": 13, "name": "ジスプロシウム", "atomic_number": 66, "description": "高性能な磁石材料。"},
    {"symbol": "Ho", "row": 9, "col": 14, "name": "ホルミウム", "atomic_number": 67, "description": "強い磁場を発生させる元素。"},
    {"symbol": "Er", "row": 9, "col": 15, "name": "エルビウム", "atomic_number": 68, "description": "ファイバー通信に使われる。"},
    {"symbol": "Tm", "row": 9, "col": 16, "name": "ツリウム", "atomic_number": 69, "description": "高温で安定した金属。"},
    {"symbol": "Yb", "row": 9, "col": 17, "name": "イッテルビウム", "atomic_number": 70, "description": "レーザーに使われる。"},
    {"symbol": "Lu", "row": 9, "col": 18, "name": "ルテチウム", "atomic_number": 71, "description": "希土類金属で、放射線測定に使われる。"},
    {"symbol": "Hf", "row": 6, "col": 4, "name": "ハフニウム", "atomic_number": 72, "description": "非常に高温に耐える金属。"},
    {"symbol": "Ta", "row": 6, "col": 5, "name": "タンタル", "atomic_number": 73, "description": "高温、腐食に耐える金属。"},
    {"symbol": "W", "row": 6, "col": 6, "name": "タングステン", "atomic_number": 74, "description": "最も高い融点を持つ金属。"},
    {"symbol": "Re", "row": 6, "col": 7, "name": "レニウム", "atomic_number": 75, "description": "高温で使用される合金。"},
    {"symbol": "Os", "row": 6, "col": 8, "name": "オスミウム", "atomic_number": 76, "description": "最も密度の高い金属。"},
    {"symbol": "Ir", "row": 6, "col": 9, "name": "イリジウム", "atomic_number": 77, "description": "高耐久性の金属。"},
    {"symbol": "Pt", "row": 6, "col": 10, "name": "白金", "atomic_number": 78, "description": "非常に耐腐食性の高い金属。"},
    {"symbol": "Au", "row": 6, "col": 11, "name": "金", "atomic_number": 79, "description": "貴金属で、ジュエリーに使われる。"},
    {"symbol": "Hg", "row": 6, "col": 12, "name": "水銀", "atomic_number": 80, "description": "常温で液体の金属。"},
    {"symbol": "Tl", "row": 6, "col": 13, "name": "タリウム", "atomic_number": 81, "description": "有毒で、放射線測定にも使われる。"},
    {"symbol": "Pb", "row": 6, "col": 14, "name": "鉛", "atomic_number": 82, "description": "有毒で、昔は水道管に使われていた。"},
    {"symbol": "Bi", "row": 6, "col": 15, "name": "ビスマス", "atomic_number": 83, "description": "低毒性の金属。"},
    {"symbol": "Po", "row": 6, "col": 16, "name": "ポロニウム", "atomic_number": 84, "description": "非常に放射能が強い元素。"},
    {"symbol": "At", "row": 6, "col": 17, "name": "アスタチウム", "atomic_number": 85, "description": "非常に希少で放射能を持つ元素。"},
    {"symbol": "Rn", "row": 6, "col": 18, "name": "ラドン", "atomic_number": 86, "description": "放射能を持つ気体。"},
    {"symbol": "Fr", "row": 7, "col": 1, "name": "フランシウム", "atomic_number": 87, "description": "非常に放射能が強い元素。"},
    {"symbol": "Ra", "row": 7, "col": 2, "name": "ラジウム", "atomic_number": 88, "description": "非常に高い放射能を持つ元素。"},
    {"symbol": "Ac", "row": 10, "col": 4, "name": "アクチニウム", "atomic_number": 89, "description": "放射能を持つ元素。"},
    {"symbol": "Th", "row": 10, "col": 5, "name": "トリウム", "atomic_number": 90, "description": "放射能を持つ元素。"},
    {"symbol": "Pa", "row": 10, "col": 6, "name": "プロトアクチニウム", "atomic_number": 91, "description": "放射能を持つ元素。"},
    {"symbol": "U", "row": 10, "col": 7, "name": "ウラン", "atomic_number": 92, "description": "核燃料として使われる。"},
    {"symbol": "Np", "row": 10, "col": 8, "name": "ネプツニウム", "atomic_number": 93, "description": "人工的に作られる元素。"},
    {"symbol": "Pu", "row": 10, "col": 9, "name": "プルトニウム", "atomic_number": 94, "description": "核兵器に使われる。"},
    {"symbol": "Am", "row": 10, "col": 10, "name": "アメリシウム", "atomic_number": 95, "description": "人工的に作られる元素。"},
    {"symbol": "Cm", "row": 10, "col": 11, "name": "キュリウム", "atomic_number": 96, "description": "人工元素。"},
    {"symbol": "Bk", "row": 10, "col": 12, "name": "バークリウム", "atomic_number": 97, "description": "人工元素。"},
    {"symbol": "Cf", "row": 10, "col": 13, "name": "カリフォルニウム", "atomic_number": 98, "description": "人工元素。"},
    {"symbol": "Es", "row": 10, "col": 14, "name": "アインスタイニウム", "atomic_number": 99, "description": "人工元素。"},
    {"symbol": "Fm", "row": 10, "col": 15, "name": "フェルミウム", "atomic_number": 100, "description": "人工元素。"},
    {"symbol": "Md", "row": 10, "col": 16, "name": "メンデレビウム", "atomic_number": 101, "description": "人工元素。"},
    {"symbol": "No", "row": 10, "col": 17, "name": "ノーベリウム", "atomic_number": 102, "description": "人工元素。"},
    {"symbol": "Lr", "row": 10, "col": 18, "name": "ローレンシウム", "atomic_number": 103, "description": "人工元素。"},
    {"symbol": "Rf", "row": 7, "col": 4, "name": "ラザホージウム", "atomic_number": 104, "description": "人工元素。"},
    {"symbol": "Db", "row": 7, "col": 5, "name": "ドブニウム", "atomic_number": 105, "description": "人工元素。"},
    {"symbol": "Sg", "row": 7, "col": 6, "name": "シーボーギウム", "atomic_number": 106, "description": "人工元素。"},
    {"symbol": "Bh", "row": 7, "col": 7, "name": "ハッシウム", "atomic_number": 107, "description": "人工元素。"},
    {"symbol": "Hs", "row": 7, "col": 8, "name": "バイコウム", "atomic_number": 108, "description": "人工元素。"},
    {"symbol": "Mt", "row": 7, "col": 9, "name": "マイトネリウム", "atomic_number": 109, "description": "人工元素。"},
    {"symbol": "Ds", "row": 7, "col": 10, "name": "ダームスタチウム", "atomic_number": 110, "description": "人工元素。"},
    {"symbol": "Rg", "row": 7, "col": 11, "name": "レニウム", "atomic_number": 111, "description": "人工元素。"},
    {"symbol": "Cn", "row": 7, "col": 12, "name": "コペルニウム", "atomic_number": 112, "description": "人工元素。"},
    {"symbol": "Nh", "row": 7, "col": 13, "name": "ニホニウム", "atomic_number": 113, "description": "人工元素。"},
    {"symbol": "Fl", "row": 7, "col": 14, "name": "フレロウム", "atomic_number": 114, "description": "人工元素。"},
    {"symbol": "Mc", "row": 7, "col": 15, "name": "モスコビウム", "atomic_number": 115, "description": "人工元素。"},
    {"symbol": "Lv", "row": 7, "col": 16, "name": "リバモリウム", "atomic_number": 116, "description": "人工元素。"},
    {"symbol": "Ts", "row": 7, "col": 17, "name": "テネシウム", "atomic_number": 117, "description": "人工元素。"},
    {"symbol": "Og", "row": 7, "col": 18, "name": "オガネソン", "atomic_number": 118, "description": "人工元素。"},
]


@app.route('/')
def index():
    return render_template('index.html', elements=elements)

@app.route('/element/<symbol>')
def get_element(symbol):
    element = next((e for e in elements if e["symbol"] == symbol), None)
    if element:
        return jsonify(element)
    else:
        return jsonify({"name": "不明", "atomic_number": "?", "description": "データがありません。"}), 404

if __name__ == '__main__':
    app.run(debug=True)
